config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  
  resources :posts, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: "---"},
    { id: 1, name: "弾き語り"},
    { id: 2, name: "オリジナル"},
    { id: 3, name: "歌ってみた"},
    { id: 4, name: "演奏してみた"},
    { id: 5, name: "その他"}
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 0, name: "---"},
    { id: 1, name: "オリジナル"},
    { id: 2, name: "邦楽"},
    { id: 3, name: "洋楽"},
    { id: 4, name: "ロック・メタル"},
    { id: 5, name: "その他"}
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image, presence: true
  validates :title, presence: true
  validates :explanation, presence: true
  validates :category_id, numericality: { other_than: 0, message: 'を選択してください'}
  validates :genre_id, numericality: { other_than: 0, message: 'を選択してください'}
  
  belongs_to :user
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, allow_blank: true, message: 'には6文字以上で、英字と数字の両方を含めて設定してください'
  validates_format_of :password_confirmation, with: PASSWORD_REGEX, allow_blank: true, message: 'には6文字以上で、英字と数字の両方を含めて設定してください'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :category_id, :genre_id, :explanation, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SSWPark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div class="main">
  <%= image_tag "IMG_2953.JPG", class: "main-post"%>
  <%# 投稿一覧 %>
  <div class='post-contents'>
    <h2 class='title'>ピックアップユーザー</h2>
    <div class="subtitle" >
      〜NEW POSTS〜
    </div>
    <ul class='post-lists'>

      <% @posts.each do |post|%>
        <li class='lists'>
          <%= link_to post_path(post.id) do %>
          <div class='post-img-content'>
            <%= image_tag post.image, class: "post-img" %>
          </div>
          <div class='post-info'>
            <h3 class='post-user-name'>
              <%#= post.user.nickname %>
            </h3>
            <div class='post-title'>
              <span><%= post.title %></span>
            </div>
          </div>
          <% end %>
        </li>
      <% end%>
    </ul>
  </div>
  <%# /投稿一覧 %>
</div>
<% if user_signed_in? %>
  <%= link_to(new_post_path, class: 'post-btn') do %>
    <span class='post-btn-text'>投稿する</span>
    <%= image_tag 'icon_129690_256.png' , size: '90x50' ,class: "post-btn-icon" %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= render "shared/header" %>
<div class="post-new-main">
  <h2 class="post-new-title">新規投稿</h2>
  <%= form_with model: @post, local: true do |f|%>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="field">
      <div class="form-content">画像
        <span class="indispensable">※必須</span><br />
      </div>
      <%= f.file_field :image, id:"post_image" %>
    </div>

    <div class="field">
      <div class="form-content">タイトル
        <span class="indispensable">※必須</span><br />
      </div>
      <%= f.text_area :title, class:"posts-text", id:"post_title" %>
    </div>

    <div class="field">
      <div class="form-content">カテゴリー
        <span class="indispensable">※必須</span><br />
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"post-category"}) %>
    </div>

    <div class="field">
      <div class="form-content">ジャンル
        <span class="indispensable">※必須</span><br />
      </div>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"post-junre"}) %>
    </div>

    <div class="field">
      <div class="form-content">説明
        <span class="indispensable">※必須</span><br />
      </div>
      <%= f.text_field :explanation, class:"posts-text", id:"post_explanation" %>
    </div>

    <div class="actions">
      <%= f.submit "投稿する", class:"post-create"  %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='header'>
  <div class='search-bar-contents'>
    <%= link_to 'SSWPark', root_path, class: 'title'%>
    <%= link_to '詳細検索', "#", class: 'detail-search' %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワード検索'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='user'>
    <ul class=lists>
      <% if user_signed_in? %>
      <li><%= link_to current_user.name, "#", class: "user-nickname" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>